# fly.toml app configuration file generated for beneficni-strapi on 2023-09-22T17:22:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beneficni-strapi"
primary_region = "ams"

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  DATABASE_CLIENT = "postgres"

[mounts]
  source="uploads"
  destination="/beneficni/public/uploads"
